tools:
  ClangFormat:
    enable: True
    version: ~=14.0
  CMakeFormat:
    enable: True
  Flake8:
    enable: True
    include: &pyfiles
        match:
        - bin/.*
        - .*\.py
  Black:
    enable: True
    include: *pyfiles

