name: check-python-flake8
on: [pull_request, push]

jobs:
  build:
    name: check-python-flake8
    runs-on: ubuntu-20.04
    # Run on external PRs, but not internal PRs as they'll be run by the push
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
        - name: Fetch repository
          uses: actions/checkout@v3
        - name: Install packages
          run: sudo apt-get update && sudo apt-get install python3-venv
        - name: Check Python Flake8
          run: bin/static-analysis --lang python
